apiVersion: v1
kind: Service
metadata:
  name: datapress-api
  namespace: datapress-recette
spec:
  type: ClusterIP
  selector:
    app: datapress-api
  ports:
    - name: http
      port: 80
      targetPort: 8000

