apiVersion: v1
kind: Service
metadata:
  name: datapress-front
  namespace: datapress-recette
spec:
  type: NodePort
  selector:
    app: datapress-front
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080

