apiVersion: apps/v1
kind: Deployment
metadata: { name: front, namespace: workshop }
spec:
  replicas: 2
  selector: { matchLabels: { app: front } }
  template:
    metadata: { labels: { app: front } }
    spec:
      containers:
      - name: front
        image: nginxdemos/hello
        env:
        - name: BANNER_TEXT
          valueFrom: { configMapKeyRef: { name: front-config, key: BANNER_TEXT } }
        ports: [{ name: http, containerPort: 80 }]
---
apiVersion: v1
kind: Service
metadata: { name: front, namespace: workshop }
spec:
  selector: { app: front }
  ports: [{ port: 80, targetPort: http }]